apiVersion: dapr.io/v1alpha1
kind: Component

metadata:
  name: pubsub

spec:
  type: pubsub.kafka

  metadata:
    - name: brokers
      value: localhost:9092

    - name: consumerGroup
      value: dapr-java-consumer

    - name: authType
      value: none